config/routes.rb
Pulse::Application.routes.draw do
  root to: "kits#index"

  resources :rhythms

  resources :kits do
    get :admin, on: :collection
  end

  resources :instruments do
    get :admin, on: :collection
  end

end

app/models/beat.rb
class Beat < ActiveRecord::Base
  belongs_to :pattern
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
    has_many :setups
    has_many :kits, through: :setups
end

app/models/kit.rb
class Kit < ActiveRecord::Base
  has_many :setups, order: "row"
  has_many :instruments, through: :setups
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :pattern
end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  belongs_to :rhythm
  has_many :notes, dependent: :destroy
  default_scope { order('row ASC') }
end

app/models/rhythm.rb
class Rhythm < ActiveRecord::Base
  has_many :patterns, dependent: :destroy
  has_many :notes, through: :patterns
  after_save {
    if self.patterns.length == 0
      8.times do |row|
        pattern = Pattern.new(
          rhythm_id: self.id,
          row: row
        )
        pattern.save()
        16.times do |col|
          note = Note.new(
            pattern_id: pattern.id,
            position: col,
            volume: 80,
            active: false
          )
          note.save()
        end
      end
    end
  }
end

app/models/setup.rb
class Setup < ActiveRecord::Base
  belongs_to :kit
  belongs_to :instrument
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]
  
  # Only allow admin access to views that modify instruments
  username = Rails.application.config.admin_username
  password = Rails.application.config.admin_password
  http_basic_authenticate_with name: username, password: password,
except: [:index, :show]
  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all
  end
  
  def admin
    @instruments = Instrument.all
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @instrument.to_json(
        except: [:created_at, :updated_at]
      ) }
    end
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render action: 'show', status: :created, location: @instrument }
      else
        format.html { render action: 'new' }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:name, :category, :sample)
    end
end

app/controllers/kits_controller.rb
class KitsController < ApplicationController
  before_action :set_kit, only: [:show, :edit, :update, :destroy]

  # Only allow admin access to views that modify kits
  username = Rails.application.config.admin_username
  password = Rails.application.config.admin_password
  http_basic_authenticate_with name: username, password: password,
except: [:index, :show]

  # GET /kits
  # GET /kits.json
  def index
    @kits = Kit.all
    @rhythms = Rhythm.all
  end

  def admin
    @kits = Kit.all
  end

  # GET /kits/1
  # GET /kits/1.json
  def show
  end

  # GET /kits/new
  def new
    @kit = Kit.new
  end

  # GET /kits/1/edit
  def edit
  end

  # POST /kits
  # POST /kits.json
  def create
    @kit = Kit.new(kit_params)

    respond_to do |format|
      if @kit.save
        format.html { redirect_to @kit, notice: 'Kit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @kit }
      else
        format.html { render action: 'new' }
        format.json { render json: @kit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kits/1
  # PATCH/PUT /kits/1.json
  def update
    respond_to do |format|
      if @kit.update(kit_params)
        format.html { redirect_to @kit, notice: 'Kit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @kit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kits/1
  # DELETE /kits/1.json
  def destroy
    @kit.destroy
    respond_to do |format|
      format.html { redirect_to kits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kit
      @kit = Kit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kit_params
      params.require(:kit).permit(:name)
    end
end

app/controllers/rhythms_controller.rb
class RhythmsController < ApplicationController
  before_action :set_rhythm, only: [:show, :edit, :update, :destroy]

  # GET /rhythms
  # GET /rhythms.json
  def index
    @rhythms = Rhythm.all
  end

  # GET /rhythms/1
  # GET /rhythms/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rhythm
      @rhythm = Rhythm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rhythm_params
      params[:rhythm]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/views/instruments/_form.html.erb
<%= form_for(@instrument) do |f| %>
  <% if @instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% @instrument.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :sample %><br>
    <%= f.text_field :sample %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instruments/admin.html.erb
<%= content_for :admin_content do %>
  <h1>Instruments</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>ID</th>
        <th>Sample</th>
        <th>Preview</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @instruments.each do |instrument| %>
        <tr>
          <td><%= instrument.name %></td>
          <td><%= instrument.category %></td>
          <td><%= instrument.id %></td>
          <td><%= instrument.sample %></td>
          <td>
            <audio controls="controls">
              <source src="<%= instrument.sample %>.wav" type="audio/wav"/>
            </audio>
          </td>
          <td><%= link_to 'Show', instrument %></td>
          <td><%= link_to 'Edit', edit_instrument_path(instrument) %></td>
          <td><%= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Instrument', new_instrument_path %>
<% end %>
<%= render template: "layouts/admin" %>

app/views/instruments/edit.html.erb
<%= content_for :admin_content do %>
  <h1>Editing instrument</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @instrument %> |
  <%= link_to 'Back', instruments_path %>
<% end %>
<%= render template: "layouts/admin" %>

app/views/instruments/index.html.erb
<div class="row">
    <div class="small-12 columns">
      <h1>Instruments</h1>
      <% @instruments.each do |instrument| %>
        <div class="instrument-pad">
          <div class="title"><%= instrument.name %></div>
          <div class="trigger-pad <%= instrument.category %>" 
            data-audio="<%= instrument.sample %>" id="<%= instrument.id %>"></div>
        </div>
      <% end %>
    </div>
</div>

app/views/instruments/new.html.erb
<%= content_for :admin_content do %>
  <h1>New instrument</h1>

  <%= render 'form' %>

  <%= link_to 'Back', instruments_path %>
<% end %>
<%= render template: "layouts/admin" %>

app/views/instruments/show.html.erb
<%= content_for :admin_content do %>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @instrument.name %>
  </p>

  <%= link_to 'Edit', edit_instrument_path(@instrument) %> |
  <%= link_to 'Back', instruments_path %>
<% end %>
<%= render template: "layouts/admin" %>

app/views/kits/_form.html.erb
<%= form_for(@kit) do |f| %>
  <% if @kit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kit.errors.count, "error") %> prohibited this kit from being saved:</h2>

      <ul>
      <% @kit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kits/admin.html.erb
<% content_for :admin_content do %>
  <h1>Listing kits</h1>

  <table>
    <thead>
      <tr>
          <th>Name</th>
          <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @kits.each do |kit| %>
        <tr>
            <td><%= kit.name %></td>
            <td><%= link_to 'Show', kit %></td>
          <td><%= link_to 'Edit', edit_kit_path(kit) %></td>
          <td><%= link_to 'Destroy', kit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Kit', new_kit_path %>
<% end %>
<%= render template: "layouts/admin" %>

app/views/kits/edit.html.erb
<% content_for :admin_content do %>
  <h1>Editing kit</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @kit %> |
  <%= link_to 'Back', kits_path %>
<% end %>
<%= render template: "layouts/admin" %>

app/views/kits/index.html.erb
<script type="text/template" id="instrument-template">
  <div class="row <%%- category %>" id="instrument-<%%- row %>">
    <div class="large-1 columns instrument">
      <p><%%- name %></p>
    </div>
    <div class="large-11 columns notes"></div>
  </div>
</script>
<script type="text/template" id="note-template">
<div class="note-inner <%% active ? null : print('inactive') %>">
  </div>
</script>
<script type="text/template" id="rhythm-template">
  <div class="large-2 large-offset-1 columns">
    <div id="play" class="button"><i class="fa fa-play"></i></div>
  </div>
  <div class="large-2 columns bpm">
    <label>BPM
      <input id="bpm" type="number" value="<%%- bpm %>" />
    </label>
  </div>
</script>
<%= render "/layouts/navbar" %>
<div id="pulse-view">
  <div class="row">
    <div id="kit" class="large-12 columns">

    </div>
  </div>
  <div id="controls" class="row controls">
    <div class="large-3 columns">
      <label>Rhythm
        <select id="rhythm-select">
          <% @rhythms.each do |rhythm| %>
            <option value="<%= rhythm.id %>"><%= rhythm.name %></option>
          <% end %>
        </select>
      </label>
    </div>
    <div class="large-3 columns">
      <label>Kit
        <select id="kit-select">
          <% @kits.each do |kit| %>
            <option value="<%= kit.id %>"><%= kit.name %></option>
          <% end %>
        </select>
      </label>
    </div>
    <div class="large-1 columns"></div>
  </div>
</div>

app/views/kits/new.html.erb
<% content_for :admin_content do %>
  <h1>New kit</h1>

  <%= render 'form' %>

  <%= link_to 'Back', kits_path %>
<% end %>
<%= render template: "layouts/admin" %>

app/views/kits/show.html.erb
<% content_for :admin_content do %>
  <p id="notice"><%= notice %></p>

    <%= link_to 'Edit', edit_kit_path(@kit) %> |
  <%= link_to 'Back', kits_path %>
<% end %>
<%= render template: "layouts/admin" %>

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">∿ Pulse</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
  </section>
</nav>

app/views/layouts/admin.html.erb
<div class="row">
  <div class="large-12 columns">
    <%= yield :admin_content %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Pulse" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/rhythms/_form.html.erb
<%= form_for(@rhythm) do |f| %>
  <% if @rhythm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rhythm.errors.count, "error") %> prohibited this rhythm from being saved:</h2>

      <ul>
      <% @rhythm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>